import { LocationImage } from './locationImage';

/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LoggedInUser {
    jwtToken?: string;
    userId?: string;
    fName?: string;
    lName?: string;
    avi?: string;
    userName?: string;
    birthPlace?: LocationImage;
    residesIn?: LocationImage;
    education?: string;
    occupationTitle?: string;
    email?: string;
    birthday: Date;
}
