/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IdentityUser } from './identityUser';
import { UserLocation } from './userLocation';


export interface User extends IdentityUser { 
    fName?: string;
    lName?: string;
    birthday: Date;
    birthPlace?: string;
    residesIn?: string;
    education?: string;
    occupationTitle?: string;
    avi?: string;
    facebookId?: number;
    userLocation?: Array<UserLocation>;
}
